# Generated by Django 2.2 on 2022-06-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscsv',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
