# Generated by Django 2.2 on 2022-09-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220710_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
